apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: events
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  selector:
    app: keycloak