apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jagoda/angular-frontend:alpine
          imagePullPolicy: Never
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "npm run start -- --host 0.0.0.0 --allowed-hosts myapp.local"
          ports:
            - containerPort: 4200
          envFrom:
            - configMapRef:
                name: app-config-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - port: 4200
      targetPort: 4200
