apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-keycloak-secrets
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-keycloak-secrets
                  key: db-password
            - name: POSTGRES_DB
              value: keycloak_db
          volumeMounts:
            - name: keycloak-db-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: keycloak-db-volume
          persistentVolumeClaim:
            claimName: keycloak-db-pvc
